### ISSUE TITLE
Нет драйвера, подходящего для вашей версии Chrome

### ISSUE THREAD

**Issue by SPluzh** [AlexDev505/AudioBookPlayer#2]
Привет! При запуске программы выходит сообщение "Нет драйвера, подходящего для вашей версии Chrome" и просьбой обновить хром. Хром в системе самый последний на данный момент 116.0.5845.111, но сообщение не пропадает.

**Comment by AlexDev505** [comment]
Привет. Проблема решена в новой версии приложения. Перед обновлением нужно удалить старую версию приложения (скачанные книги при этом не исчезнут, но вам нужно запомнить путь к папке с книгами, он Вам пригодится). Скачать обновление можно [на странице релиза](https://github.com/AlexDev505/AudioBookPlayer/releases/latest). После установки в разделе настроек измените путь к папке с файлами на тот, который был раньше.

**Comment by mediaexplorer74** [comment]
> [@SPluzh](https://github.com/SPluzh), Привет. Проблема решена в новой версии приложения. 

Алекс, а реально 32битную версию приложения смастерить? Чтоб на древнющем планшете Irbis tw44 матушке слушать аудиокниги...
