### ISSUE TITLE
AB Player выводит сообщение "Плеер пока недоступен

### ISSUE THREAD

**Issue by ew6nm** [AlexDev505/AudioBookPlayer#3]
Windows 11.

**Comment by AlexDev505** [comment]
Привет, @ew6nm. Я пока что не стал добавлять плеер в приложение, из-за не надобности лично мне 😅
Я могу заняться реализацией плеера, если он нужен. Если это так, дайте знать, я всегда готов развивать это приложение ✌️

**Comment by AlexDev505** [comment]
@persoun, Привет. В ближайшем будущем я начну заниматься реализацией плеера.

**Comment by AlexDev505** [comment]
@persoun, привет. Плеер можно уже можно попробовать в [новой версии](https://github.com/AlexDev505/AudioBookPlayer/releases/tag/2.1.0-betta.0).
В этом релизе еще есть некоторые сбои, я устраню их со временем. Вы можете обновить приложение скачав установочный файл со [страницы релиза](https://github.com/AlexDev505/AudioBookPlayer/releases/tag/2.1.0-betta.0) или в приложении, нажав на всплывающее сообщение, которое появится вскоре после запуска.

**Comment by AlexDev505** [comment]
Готово обновление 2.1.0. Как обновиться, я описал в посте выше. [Страница релиза](https://github.com/AlexDev505/AudioBookPlayer/releases/tag/2.1.0).
@ew6nm @persoun
